name: moneta
description: "Versão mobile do sistema de reembolso de despesar (Moneta)."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  dio: ^5.5.0
  shared_preferences: ^2.2.3
  provider: ^6.1.2
  string_validator: ^1.1.0
  json_converter: ^2.0.0
  liquid_pull_to_refresh: ^3.0.1
  collection: ^1.18.0
  flutter_slidable: ^3.1.0
  currency_text_input_formatter: ^2.2.3
  flutter_widget_from_html: ^0.15.1
  rxdart: ^0.27.7
  badges: ^3.1.2
  universal_html: ^2.2.4
  path: ^1.9.0
  image_picker_web: ^4.0.0
  http: ^1.2.1
  image_picker: ^1.1.2 #remover depois 
  photo_view: ^0.15.0
  image: ^4.2.0 
  file_picker: ^8.0.6
  flutter_pdfview: ^1.3.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/icons/BR.png
    - assets/icons/ES.png
    - assets/icons/US.png
    - assets/logos/Logo-Marko_FC.png
    - assets/icons/pwa.png
    - assets/images/background.jpg
    - assets/images/background_mobile.jpg

  fonts:
    - family: Visby
      fonts:
        - asset: assets/fonts/Visby_Bold_Italic.ttf
        - asset: assets/fonts/Visby_Regular.ttf
          weight: 700